import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sidebar for reports - automatically generated from /docs/reports folder
  reportsSidebar: [
    {
      type: 'category',
      label: 'Statistical Reports',
      items: [{type: 'autogenerated', dirName: 'reports'}],
      collapsed: false,
    },
  ],
};

export default sidebars;
